language: node_js
services:
- mongodb
notifications:
  slack:
    secure: sYddriSUL8euofUypLuBsXkAOFHdJTXFxGKHnlgfNLxe8YtvFkaCeRt/6iiShNL5B4Y6htFDzokKRtQGr435KMtP5JQY6rDC0XRUJ2llUKs4hN24OqMUAz9+EKsVz/POFG8m7qxweml3OE3hIzjdbLHFMKeY6E1Va7WEYzbSQ1jac7CdruCKnAOge4IO3jdYpOPAFu1gektodEKG7wfA0Tg8yFUCNnJzWcm8Ff/GD68IX1USP5B/BsqjvfZlD+Q52biWQ8Winzp6YwLlZDkHOnvPGRWqLSZtEkcr6CdRzH618LfNAC+O1vXITg7Bc72eRuXgsoiSp6fdoKt9rWlomGItdfRIJTxmtu+CuayH/R+RYgBUxL0iS2bGFTTckiNKVicMaWBa3evlXAlEVYMwP4n86s8+yiepJZ3Gy1wOVFGRiGdKp/4dyueKQWl9VpA85BLaZltYS5oi8o3WlNhK+NQffyryQL99rt2ZxZ/dQ2hMgmfhjg/xhf8UrLCEsm0NS51OR13s+9mub/+nKI3g6p4mVwsQSsitil/Bt3Lm9ViogLA94Prpfw97ex+/KJ1iPprBtaM6tq1iN2/PqUY04M7Tm5IGfVP4C36qjq7bmyMKO92xHezJqxH13TM2axoAIJAWFoiROwClwDrO9nrjmHIjSHjtcwlSX5bvyORIpk4=
